### ISSUE TITLE
Facing Error while Quantizaing the Yolov3 Caffe Model

### ISSUE THREAD

**Issue by Darshcg** [lp6m/tiny_yolov3_face_mask_detect#1]
Hi @lp6m,

Thanks for your tutorials,

I have custom trained the Yolov3 model and I want to do inference on DPU with Ultra 96v2. I have followed your tutorial(https://www.hackster.io/yasuhironitta/real-time-tiny-yolov3-face-mask-detection-on-ultra96v2-63a70c).
I am trying to convert the .elf file for the YoloV3 model(.weights and .cfg) using the Vitis AI container.  
But, when I am doing the Quantisation, I am facing error as:

```
E0410 03:14:58.992400 202 io.cpp:145] Could not open or find file /workspace/work/quantization/Data/.jpg
I0410 03:14:58.992415 190 net.cpp:409] layer49-shortcut_layer49-shortcut_0_split -> layer49-shortcut_layer49-shortcut_0_split_1
F0410 03:14:58.992424 202 image_data_layer.cpp:132] Check failed: cv_img.data Could not load .jpg

```
I am attaching the verbose below
![image](https://user-images.githubusercontent.com/48723743/114304174-72ded700-9aef-11eb-9eee-215742d56fd3.png)

I am not sure why I am facing this issue. Can you please help me to resolve this issue?

Thanks,
Darshan

**Comment by lp6m** [comment]
@Darshcg 
Sorry for late reply.  
The cause of this error is that the data used for calibration in the quantization flow has not been loaded.  
Modify the model definition `.prototxt`  for quantization to specify the quantization image list txt path.
https://github.com/lp6m/tiny_yolov3_face_mask_detect/blob/master/host/quantization/yolov3.prototxt#L22
