### ISSUE TITLE
What is the version of Vitis-ai-gpu？

### ISSUE THREAD

**Issue by gaoxw1030** [lp6m/tiny_yolov3_face_mask_detect#2]

**Comment by gaoxw1030** [comment]
please share the ULTRA96V2.dcf.

**Comment by gaoxw1030** [comment]
could you provide the custom.json

**Comment by lp6m** [comment]
Please see this article: https://www.hackster.io/yasuhironitta/real-time-tiny-yolov3-face-mask-detection-on-ultra96v2-63a70c
This project use VitisAI v1.1.
